### ISSUE TITLE
🍴 Scout-App 2 Beta Testers Needed!  -  Sign up here 🍴

### ISSUE THREAD

**Issue by TheJaredWilcurt** [mhs/scout-app#230]
### Scout-App will soon be getting it's first update since 2012!

Here's a look at **Scout-App 2**:

![scout-app-2-dev](https://cloud.githubusercontent.com/assets/4629794/14044313/53388aaa-f265-11e5-8031-d18a53253a93.png)

The [to-do list](https://github.com/TheJaredWilcurt/scout-app#project-management) of features and bug fixes is almost complete. We hope to have version to ready for the public by this time next month. Beta testing will start as soon as the last 4 items on the [To Do](https://github.com/TheJaredWilcurt/scout-app#project-management) list for phase 1 are complete.

## You can sign up to be a **Beta Tester** below:

Post any [food emoji](http://www.emoji-cheat-sheet.com/#emoji-objects) below, like `:pizza:` and you will be notified when there is a beta version to try out.

:pizza: :hamburger: :fries:

**Comment by StephanRaab** [comment]
:rice_ball:

**Comment by zdennis** [comment]
@TheJaredWilcurt, sorry I haven't been able to contribute, but I've been watching from a distance and I wanted to say it's looking great!

**Comment by Brockenstein** [comment]
:ramen:

**Comment by slynchoreilly** [comment]
:pizza:

**Comment by keypixel** [comment]
:pizza: I'd love to give it a run through!

**Comment by eyleron** [comment]
:icecream:

**Comment by nocturnalguru** [comment]
:green_apple:

**Comment by su1ts** [comment]
(fries)

**Comment by gabyferman** [comment]
:pizza:

**Comment by noedlm** [comment]
:rice_ball:

**Comment by matpulis** [comment]
:pizza:

**Comment by gmt-it** [comment]
:pizza:

**Comment by silatechnology** [comment]
:pizza:

**Comment by HoiJean** [comment]
:pizza:

**Comment by ypmits** [comment]
:pizza:

**Comment by TheJaredWilcurt** [comment]
@StephanRaab @zdennis @Brockenstein @slynchoreilly @keypixel @eyleron @nocturnalguru @su1ts @gabyferman @noedlm @matpulis @gmt-it @silatechnology @HoiJean @ypmits 

# You have been invited to the Scout-App 2 Beta Test!

A lot of :pizza: lovers here.

For others who got here late, you can come too. :smile_cat:

* * *

<h1 align="center" style="font-size:49px">
:arrow_right: :arrow_right: <b><a href="https://github.com/TheJaredWilcurt/scout-app/releases" font-size="59px">Scout-App 2 Beta Download</a></b> :arrow_left: :arrow_left:
</h1>

* * *

**Comment by mchervee** [comment]
Hi, I actually test the 2beta version :-)

**Comment by TheJaredWilcurt** [comment]
@mchervee 

**Cosmetic:**

* French *About* has been updated. This will be reflected in future releases. If you see anything else that could be better translated, please let me know.
* Standard commands to kill the app should work, like Alt+F4 in Windows and Ubuntu both work. I know that cut/copy/paste commands didn't work on OSX, so I had to manually add them. This may be the same case here. Will test later and fix if needed.

* * *

**Feature Request:**

* Clear all alerts and messags at once. [Added to Phase 5 of the README](https://github.com/TheJaredWilcurt/scout-app#phase-5-bug-fixesadditional-featuresmaintenance)

* * *

**Bug:**

I'm unable to reproduce this bug. I tried it in SassMeister and then locally in a project that matches the code in SassMeister and with all combinations of development and production and output settings it worked fine.

* http://www.sassmeister.com/gist/dba6d498ff86e697d545595789bd2c04

Scout-App 2 uses Node-Sass and LibSass which is built from SassC. So there are some differences between the C version and the Ruby version.

You should test your code on SassMeister and make sure that it works with LibSass on there. If it doesn't then there's nothing I'll be able to do to fix that, you'll need to [file an issue with LibSass](https://github.com/sass/libsass/issues).

If you **can** get it to work on SassMeister but it still has issues on Scout-App 2, then send me the SassMeister link and I'll see if I can reproduce it.

**Comment by TheJaredWilcurt** [comment]
@mchervee 

<h1 align="center" style="font-size:49px">
:arrow_right: :arrow_right: <b><a href="https://github.com/TheJaredWilcurt/scout-app/releases" font-size="59px">Scout-App 2 Beta 2 Download</a></b> :arrow_left: :arrow_left:
</h1>

**Comment by mchervee** [comment]
About the bug
I use the a "prestashop" site (and there is a lot of sass files, with a lot of dependencies)
I'm not able to reproduce it with sassmeister too…

While checking my own files, I noticed that the string "-owg(" (see previous post "resulting css from 2ß" -> 1st line), does not exist in my whole files (nor in mixin nor in… everything else). So it may be an buggy automation from the sass core?

---
Edit:
I tried differently. Seems that this "bug" really com from the core (compass) automation.
I was able to reproduce this error without any related mixin (aka "@include background-image([…])" produces the same results :(
So I override this behavior by creating my custom mixin (with an underscore) : "@include background_image([…])" 
All works well, no more resulting bug :)
…So much ado about nothing, this bug was not related to your app ;)

**Comment by mchervee** [comment]
Another thing (Bug/request? …don't know)

How to set a recursive project / folder sass?
In 0.7.1 version, I select my "sass" folder and all folders inside were automatically included during compile
In the 2ß version,  I select my "sass" folder but only the root folder is included during compile
(PS: my prestashop's sass files are made with: a root folder, 4 sub-level folders, and some sub-level folders more : the total of sass files is about 120 different files!!!)

bye

**Comment by TheJaredWilcurt** [comment]
@mchervee The recursive processing is a good point. I meant to do that early on and got sidetracked with UI work. I'm not sure on prioritizing this over creating of the website or developing better automated build tools. Right now I'm building for each OS manually. This is on my radar and is important.

Compass only works with Ruby. Scout-App 2 uses Node-Sass instead of Ruby-Sass. So the only part of Compass we support is compass-mixins, which are built in to Scout-App, along with [many other popular Sass mixin libraries](https://github.com/TheJaredWilcurt/scout-app#supportedbuilt-in-mixin-libraries).

The closest thing to Compass for Node-Sass is [EyeGlass](https://github.com/sass-eyeglass/eyeglass) which I'll look into to see if it's a viable option to include it in Scout-App. It's meant to be mostly compatible with stylesheets written with Compass in mind, with minimal amounts of change required.

**Comment by PhilipsIron** [comment]
Don't know if it's the right place where to ask but in the scout 2 beta 2 version got this issue with imports:
I click on the play button and it's all ok.
When I make a change on imported scss file and save it it always gives me this error

> File to import not found or unreadable: subfolder/_myimportedfile.scss
The file is in a subdirectory.
If I click stop and play again it works without errors, but obviously it's stupid click stop and play everytime I make a change on a scss file...
Is it a scout bug? Thanks guys.

**Comment by TheJaredWilcurt** [comment]
@PhilipsIron

1. Is there a public repo that I can use to reproduce this. Or can you make a simplified version of the repo where this is happening and link to it here.
* What OS are you on
* Did that error message occur in the app (red message) or in the console (Dev Tools). If it's in the app UI, does the console say anything different.
* Is there anything in the file path that could cause issues (weird characters or symbols)
* Does relocating your project to a different drive or closer to the root of your drive have any effect

**Comment by PhilipsIron** [comment]
@TheJaredWilcurt 
1. No, but the structure is very very simple: [structure](http://i.imgur.com/ecKwDI6.jpg)
2. Windows 7 64bit. Don't know if it's a problem but the project is in the xampp localhost folder.
3. Both app (basic theme so it's blue, not red) and the console. [take a look](http://i.imgur.com/qArXhD9.jpg)
4. Nothing strange on paths.
5. No effect.

Hope my infos are useful

**Comment by TheJaredWilcurt** [comment]
@PhilipsIron I attempted to reproduce this bug but could not. Here is a video of the attempt:

* https://youtu.be/RwYCMRHmRek

I tried in both the latest build (2.0.2) and the Scout-App 2 Beta 2 release (2.0.1) (13 commits apart). I tried with every combination of production and output settings. And also tried many variations of style of import.

**Comment by PhilipsIron** [comment]
@TheJaredWilcurt 
wow, even a vidieo! thank you for your time spent in tryin to help me.

After your reply I've tried whatever things came to my mind, even the most stupid ever.
Things such as shut off firewall, antivirus, xampp apache server etc...
I've made some progress in the end, cause I've tried adobe brackets code editor instead of sublime text.
And it worked fine and dandy! Tried also notepad and pspad editors. All ok.
I would never have thought that it was because of the editor. Bah.

Now the weird thing is that I've seen that in the video you've used Sublime text 3 (?)
and all was ok, while the 2 versions of sublime text editor that I have

> Sublime Text 2 (v.2.0.2 build 2221 - Unregistered)
> Sublime Text 3 (build 3103 - Unregistered)

give me the issue with scout. Maybe the unregistered factor? Or different builds? Mystery...

Anyway it's not a scout-showstopper anymore for me since I can go back using brackets editor,
but I think it's important that I write here about my experience so if anyone, for whatever mysterious reason will have the same issue, he can know the cause.

Thank you again for your support.

**Comment by TheJaredWilcurt** [comment]
@PhilipsIron 

So what's happening is that Sublime Text has access to the file and isn't letting other executables read/write to it. This isn't so much an issue with Sublime, as it is with Windows. As you saw in the video, I'm using Sublime as well and it's working fine. The only difference between ST Registered and Free is that it occasionally displays a nag alert. This has no affect on how it accesses files. Both versions are identical, paying for it just skips one line of code when you save.

I would still highly recommend ST over Atom/Brackets/MS Code as they are all slower, don't have the same quality of keyboard shortcuts, and are lacking in quality plugins and customization options. They're just the poor-man's knock offs of Sublime. [Here are some tips on customizing Sublime](http://projectsunday.github.io/Public/UbuntuVMSetup.html#CustomizeSublime). But all of that is unrelated.

In most cases on Windows, the problem can be solved by a reboot/log off and back in, as this will kill any file handles that have gone awry.  If you're familiar with Process Explorer, it can be used to close any connections between a file and an executable without the need for a reboot, though that's a little more advanced, so for most people I would just  tell them to reboot. Obviously that's only useful if this happens rarely.

You could also try dragging your project folder into Sublime and seeing if having the folder in ST makes a difference. I know that it does handle projects differently when their folder is in there (especially as it relates to search). So it's possible it could handle file access differently too.

Either way, I'm happy this is an OS/user specific thing, and not a bug in my dependencies (chokidar/node-sass). If it was a bug in my code I would just fix it, but if it were a dependency all I could do is report it and hope it gets fixed.

 If you find anything else wrong with Scout-App or have suggestions you can use this form:

* [Scout-App 2 Bug Report Form](https://github.com/mhs/scout-app/issues/new?title=SA2%20-%20&body=OS%3A%20%0DInformation%20from%20Dev%20Tools%3A%20%0D%0D%28Attach%20screenshot%20below%29)

**Comment by PhilipsIron** [comment]
@TheJaredWilcurt 
Thanks I've finally managed to fix the issue of ST, I know it's clear that it's offtopic  but it's right to let people know what's the problem and how to fix it in case someone has the same issue.
It's a bit tangled to explain (because for some weird reason it works contrariwise in my specific case) but I hope I'm clear enough.

ST uses an optional feature called "**atomic save**". 
Basically instead of saving the file you've edited, it creates a temp file, deletes the original and then rename the temp file with the original name.
So far so good, we have unveiled the mystery why scout can't find the file.
Now, this option, after the whole windows world complained about it, was set to false by default.
You can see it in Preferences -> Settings - Default.

And that's my specific weird case:
Even though my atomic save is set to false by default, it seems to be enabled anyway.
So I've tried a dirty trick by setting it to true through Preferences -> Settings - User
`"atomic_save": true,`
And Scout had no problems anymore into finding the file. Yay!
I've also thought that maybe the "atomic save" represents the straight save on the original file but reading through ST discussions, it doesn't seems like that, so I must have been kissed by some evil troll entity. ;)

I thank you again for your kindness and support. Case closed :)

**Comment by TheJaredWilcurt** [comment]
Beta's are done, Version 2 has officially been released. Closing this.

* * *

<h1 align="center" style="font-size:49px">
:arrow_right: :arrow_right: <b><a href="http://scout-app.io" font-size="59px">Scout-App 2 Official Release</a></b> :arrow_left: :arrow_left:
</h1>

* * *
